name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Run Unit Tests
        run: pio test -e native -vv

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: .pio/build/native/

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - Heltec_v3_companion_radio_ble
          - RAK_4631_companion_radio_ble
          - LilyGo_T3S3_sx1276_companion_radio_usb
          - Xiao_rp2040_companion_radio_usb
          - wio-e5-mini_repeater
          - LilyGo_Tlora_C6_repeater_
          - wio_wm1110_room_server
          - Tbeam_SX1262_room_server
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-environment

      - name: Build ${{ matrix.environment }}
        run: pio run -e ${{ matrix.environment }}
